/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frontend.java
 *
 * Created on 15.05.2009, 16:14:01
 */
package wiigeegui;

import org.wiigee.control.WiimoteWiigee;
import org.wiigee.device.Wiimote;
import org.wiigee.event.AccelerationEvent;
import org.wiigee.event.ButtonPressedEvent;
import org.wiigee.event.ButtonReleasedEvent;
import org.wiigee.event.AccelerationListener;
import org.wiigee.event.GestureEvent;
import org.wiigee.event.GestureListener;
import org.wiigee.event.MotionStartEvent;
import org.wiigee.event.MotionStopEvent;
import org.wiigee.event.RotationEvent;
import org.wiigee.event.RotationSpeedEvent;
import org.wiigee.event.StateEvent;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileFilter;
import org.wiigee.event.ButtonListener;
import org.wiigee.event.RotationListener;
import org.wiigee.util.Log;


/**
 *
 * @author bepo
 */
public class Frontend extends javax.swing.JFrame implements GestureListener,
        AccelerationListener, ButtonListener, RotationListener {

    private WiimoteWiigee wiigee;
    private Wiimote wiimote;
    private Vector<String> gestureMeanings;

    /** Creates new form Frontend */
    public Frontend() {
        this.wiigee = new WiimoteWiigee();
        this.gestureMeanings = new Vector<String>();
        initComponents();
    }

    public void gestureReceived(GestureEvent event) {
        this.gestureField.setBackground(Color.GREEN);
        this.gestureField.setForeground(Color.WHITE);
        this.gestureField.setText("Gesture " + this.gestureMeanings.elementAt(event.getId()) + " received.");
        this.appendToConsole("Gesture "+this.gestureMeanings.elementAt(event.getId())+" received.");
    }

    public void stateReceived(StateEvent event) {
        System.out.println("statechange received.");
    }

    public void accelerationReceived(AccelerationEvent event) {
        this.graphPanel1.accelerate(event);
    }

    public void buttonPressReceived(ButtonPressedEvent event) {
        this.wiimotePanel1.changeState(event);
        if (event.isRecognitionInitEvent()) {
            this.recognitionField.setBackground(Color.GREEN);
        } else if (event.isTrainInitEvent()) {
            this.trainingField.setBackground(Color.GREEN);
        } else if (event.isCloseGestureInitEvent()) {
            // show a dialog to enter gesture meaning
            this.getGestureMeaningDialog.setVisible(true);
        }

        if(event.getButton()==Wiimote.BUTTON_MINUS) {
            Log.write("FILTER RESET!");
            this.wiimote.resetFilters();
        }
    }

    public void buttonReleaseReceived(ButtonReleasedEvent event) {
        this.wiimotePanel1.changeState(event);
        this.recognitionField.setBackground(Color.WHITE);
        this.trainingField.setBackground(Color.WHITE);
    }

    public void motionStartReceived(MotionStartEvent event) {
        this.inMotionField.setBackground(Color.GREEN);
    }

    public void motionStopReceived(MotionStopEvent event) {
        this.inMotionField.setBackground(Color.WHITE);
    }

    public void rotationSpeedReceived(RotationSpeedEvent event) {
        Log.write("Rotspeed: psi="+event.getPsi()+
                " theta="+event.getTheta()+
                " phi="+event.getPhi());
    }

    public void rotationReceived(RotationEvent event) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void appendToConsole(String s) {
        this.consoleTextArea.append(s+"\n\r");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        selectWiimoteDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        connectWiimoteButton = new javax.swing.JButton();
        wiimotesMacTextField = new javax.swing.JTextField();
        scanWiimoteDialog = new javax.swing.JDialog();
        scanWiimoteStatusLabel = new javax.swing.JLabel();
        scanWiimoteApproveButton = new javax.swing.JButton();
        getGestureMeaningDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        gestureMeaningTextField = new javax.swing.JTextField();
        setGestureMeaningButton = new javax.swing.JButton();
        consoleScrollPane = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        graphPanel1 = new wiigeegui.GraphPanel();
        inMotionField = new javax.swing.JTextField();
        recognitionField = new javax.swing.JTextField();
        trainingField = new javax.swing.JTextField();
        gestureField = new javax.swing.JTextField();
        wiimotePanel1 = new wiigeegui.WiimotePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        wiimoteMenu = new javax.swing.JMenu();
        connectWiimoteItem = new javax.swing.JMenuItem();
        autoconnectWiimoteItem = new javax.swing.JMenuItem();
        disconnectWiimoteItem = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        loadGesturesItem = new javax.swing.JMenuItem();
        saveGesturesItem = new javax.swing.JMenuItem();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setFileFilter(new FileFilter() {
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".wgs") || f.isDirectory();
            }

            public String getDescription() {
                return "wiigee Gestureset (*.wgs)";
            }
        });

        selectWiimoteDialog.setTitle("Connect");
        selectWiimoteDialog.setModal(true);
        selectWiimoteDialog.setName("selectWiimote"); // NOI18N

        jLabel1.setText("Please enter the Wiimote's Bluetooth MAC:");

        connectWiimoteButton.setText("Connect");
        connectWiimoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectWiimoteButtonActionPerformed(evt);
            }
        });

        wiimotesMacTextField.setText("00:1E:35:0F:40:BA");

        org.jdesktop.layout.GroupLayout selectWiimoteDialogLayout = new org.jdesktop.layout.GroupLayout(selectWiimoteDialog.getContentPane());
        selectWiimoteDialog.getContentPane().setLayout(selectWiimoteDialogLayout);
        selectWiimoteDialogLayout.setHorizontalGroup(
            selectWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(selectWiimoteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(selectWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(connectWiimoteButton)
                    .add(selectWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, wiimotesMacTextField)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectWiimoteDialogLayout.setVerticalGroup(
            selectWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(selectWiimoteDialogLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(wiimotesMacTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(connectWiimoteButton)
                .addContainerGap())
        );

        scanWiimoteDialog.setTitle("Scanning...");
        scanWiimoteDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scanWiimoteDialog.setEnabled(false);
        scanWiimoteDialog.setModal(true);
        scanWiimoteDialog.setName("scanWiimote"); // NOI18N
        scanWiimoteDialog.setResizable(false);
        scanWiimoteDialog.setUndecorated(true);

        scanWiimoteStatusLabel.setText("Please press Button A and B on the Wiimote...");

        scanWiimoteApproveButton.setText("OK");
        scanWiimoteApproveButton.setEnabled(false);
        scanWiimoteApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanWiimoteApproveButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout scanWiimoteDialogLayout = new org.jdesktop.layout.GroupLayout(scanWiimoteDialog.getContentPane());
        scanWiimoteDialog.getContentPane().setLayout(scanWiimoteDialogLayout);
        scanWiimoteDialogLayout.setHorizontalGroup(
            scanWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scanWiimoteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(scanWiimoteStatusLabel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scanWiimoteDialogLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .add(scanWiimoteApproveButton)
                .addContainerGap())
        );
        scanWiimoteDialogLayout.setVerticalGroup(
            scanWiimoteDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scanWiimoteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(scanWiimoteStatusLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scanWiimoteApproveButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getGestureMeaningDialog.setModal(true);

        jLabel2.setText("Please enter the meaning of the trained gesture:");

        gestureMeaningTextField.setText("e.g. Circle");

        setGestureMeaningButton.setText("OK");
        setGestureMeaningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGestureMeaningButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout getGestureMeaningDialogLayout = new org.jdesktop.layout.GroupLayout(getGestureMeaningDialog.getContentPane());
        getGestureMeaningDialog.getContentPane().setLayout(getGestureMeaningDialogLayout);
        getGestureMeaningDialogLayout.setHorizontalGroup(
            getGestureMeaningDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(getGestureMeaningDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(getGestureMeaningDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, gestureMeaningTextField)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, getGestureMeaningDialogLayout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .add(setGestureMeaningButton)
                .addContainerGap())
        );
        getGestureMeaningDialogLayout.setVerticalGroup(
            getGestureMeaningDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(getGestureMeaningDialogLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gestureMeaningTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(setGestureMeaningButton)
                .add(9, 9, 9))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wiigee Demo-GUI");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        consoleScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        consoleTextArea.setColumns(20);
        consoleTextArea.setLineWrap(true);
        consoleTextArea.setRows(5);
        consoleScrollPane.setViewportView(consoleTextArea);

        graphPanel1.setBackground(new java.awt.Color(255, 255, 255));
        graphPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.layout.GroupLayout graphPanel1Layout = new org.jdesktop.layout.GroupLayout(graphPanel1);
        graphPanel1.setLayout(graphPanel1Layout);
        graphPanel1Layout.setHorizontalGroup(
            graphPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 417, Short.MAX_VALUE)
        );
        graphPanel1Layout.setVerticalGroup(
            graphPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 213, Short.MAX_VALUE)
        );

        inMotionField.setEditable(false);
        inMotionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inMotionField.setText("In Motion");

        recognitionField.setEditable(false);
        recognitionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recognitionField.setText("Recognition");

        trainingField.setEditable(false);
        trainingField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trainingField.setText("Training");

        gestureField.setEditable(false);
        gestureField.setFont(new java.awt.Font("Lucida Grande", 1, 15));
        gestureField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        wiimotePanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.layout.GroupLayout wiimotePanel1Layout = new org.jdesktop.layout.GroupLayout(wiimotePanel1);
        wiimotePanel1.setLayout(wiimotePanel1Layout);
        wiimotePanel1Layout.setHorizontalGroup(
            wiimotePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 158, Short.MAX_VALUE)
        );
        wiimotePanel1Layout.setVerticalGroup(
            wiimotePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 649, Short.MAX_VALUE)
        );

        wiimoteMenu.setText("Wiimote");

        connectWiimoteItem.setText("Connect...");
        connectWiimoteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectWiimoteItemActionPerformed(evt);
            }
        });
        wiimoteMenu.add(connectWiimoteItem);

        autoconnectWiimoteItem.setText("Autoconnect");
        autoconnectWiimoteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoconnectWiimoteItemActionPerformed(evt);
            }
        });
        wiimoteMenu.add(autoconnectWiimoteItem);

        disconnectWiimoteItem.setText("Disconnect");
        disconnectWiimoteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectWiimoteItemActionPerformed(evt);
            }
        });
        wiimoteMenu.add(disconnectWiimoteItem);

        jMenuBar1.add(wiimoteMenu);

        fileMenu.setText("File");

        loadGesturesItem.setText("Load Gestureset");
        loadGesturesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGesturesItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadGesturesItem);

        saveGesturesItem.setText("Save Gestureset");
        saveGesturesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGesturesItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveGesturesItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(wiimotePanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(consoleScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .add(gestureField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .add(graphPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(inMotionField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(recognitionField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(trainingField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(wiimotePanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(graphPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                            .add(inMotionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(recognitionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(trainingField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gestureField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(consoleScrollPane)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveGesturesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGesturesItemActionPerformed
        BufferedWriter out = null;
        try {
            int retVal = this.jFileChooser1.showSaveDialog(fileMenu);

            if (retVal == jFileChooser1.APPROVE_OPTION) {
                // save the gesture set file
                File f = jFileChooser1.getSelectedFile();
                out = new BufferedWriter(new FileWriter(f));

                // save the specified gestures and write text
                for (int i = 0; i < this.gestureMeanings.size(); i++) {
                    this.wiimote.saveGesture(i, f.getParent()+"/"+this.gestureMeanings.elementAt(i));
                    out.write(this.gestureMeanings.elementAt(i));
                    out.newLine();
                }
                
                out.flush();
            }
        } catch (IOException ex) {
            Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveGesturesItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (wiimote != null) {
            wiimote.disconnect();
        }
    }//GEN-LAST:event_formWindowClosing

    private void autoconnectWiimoteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoconnectWiimoteItemActionPerformed
        //this.scanWiimoteDialog.setVisible(true);
        try {
            Wiimote wm = this.wiigee.getDevice();
            if (wm != null) {
                this.scanWiimoteStatusLabel.setText("Found a Wiimote!");
                this.scanWiimoteApproveButton.setEnabled(true);
                this.wiimote = wm;
                this.setupWiimote();
            }
        } catch (IOException ex) {
            this.scanWiimoteStatusLabel.setText("No Wiimote found!");
            this.scanWiimoteApproveButton.setEnabled(true);
            Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_autoconnectWiimoteItemActionPerformed

    private void connectWiimoteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectWiimoteItemActionPerformed
        this.selectWiimoteDialog.setVisible(true);
    }//GEN-LAST:event_connectWiimoteItemActionPerformed

    private void disconnectWiimoteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectWiimoteItemActionPerformed
        if (this.wiimote != null) {
            this.wiimote.disconnect();
        }
    }//GEN-LAST:event_disconnectWiimoteItemActionPerformed

    private void scanWiimoteApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanWiimoteApproveButtonActionPerformed
        this.scanWiimoteDialog.setVisible(false);
    }//GEN-LAST:event_scanWiimoteApproveButtonActionPerformed

    private void connectWiimoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectWiimoteButtonActionPerformed
        try { // manual connect: 001E350F40BA
            this.selectWiimoteDialog.setVisible(false);
            this.wiimote = new Wiimote(this.wiimotesMacTextField.getText(), true, true);
            this.setupWiimote();
        } catch (IOException ex) {
            Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_connectWiimoteButtonActionPerformed

    private void setGestureMeaningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGestureMeaningButtonActionPerformed
        this.gestureMeanings.add(this.gestureMeaningTextField.getText());
        this.getGestureMeaningDialog.setVisible(false);
    }//GEN-LAST:event_setGestureMeaningButtonActionPerformed

    private void loadGesturesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGesturesItemActionPerformed
        BufferedReader in = null;
        try {
            int retVal = this.jFileChooser1.showOpenDialog(fileMenu);

            if (retVal == jFileChooser1.APPROVE_OPTION) {
                // open the gesture set file
                File f = jFileChooser1.getSelectedFile();
                in = new BufferedReader(new FileReader(f));

                // load the single gestures
                String line;
                while(in.ready()) {
                    line = in.readLine();
                    this.wiimote.loadGesture(f.getParent()+"/"+line);
                    this.gestureMeanings.add(line);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(Frontend.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loadGesturesItemActionPerformed

    private void setupWiimote() {
        try {
            this.wiimote.disableAccelerationSensors();
            this.wiimote.enableWiiMotionPlus();
            } catch(Exception e) {
                Log.write("Grosser Mist: setupWiimote()");
                e.printStackTrace();
            }

        this.wiimote.addAccelerationListener(this);
        this.wiimote.addButtonListener(this);
        this.wiimote.addRotationListener(this);
        this.wiimote.addGestureListener(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem autoconnectWiimoteItem;
    private javax.swing.JButton connectWiimoteButton;
    private javax.swing.JMenuItem connectWiimoteItem;
    private javax.swing.JScrollPane consoleScrollPane;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JMenuItem disconnectWiimoteItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField gestureField;
    private javax.swing.JTextField gestureMeaningTextField;
    private javax.swing.JDialog getGestureMeaningDialog;
    private wiigeegui.GraphPanel graphPanel1;
    private javax.swing.JTextField inMotionField;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadGesturesItem;
    private javax.swing.JTextField recognitionField;
    private javax.swing.JMenuItem saveGesturesItem;
    private javax.swing.JButton scanWiimoteApproveButton;
    private javax.swing.JDialog scanWiimoteDialog;
    private javax.swing.JLabel scanWiimoteStatusLabel;
    private javax.swing.JDialog selectWiimoteDialog;
    private javax.swing.JButton setGestureMeaningButton;
    private javax.swing.JTextField trainingField;
    private javax.swing.JMenu wiimoteMenu;
    private wiigeegui.WiimotePanel wiimotePanel1;
    private javax.swing.JTextField wiimotesMacTextField;
    // End of variables declaration//GEN-END:variables

}
