\thispagestyle{empty}
% zentriert: 0.26cm
\hoffset=0.4cm
\begin{center}
{~}\\
\vspace{8cm}
{\begin{minipage}[t]{10cm}
\centering
\LARGE
{\bf wiigee}\\
\vspace{0.2cm}
\large
Accelerometerbased\\
3D Gesture Recognition
\end{minipage}}\\
\vspace{1cm}
{\bf -- Manual --}\\
\vspace{7.5cm}
{\small Benjamin Poppinga}\\
{\footnotesize benjamin@wiigee.org}\\
\vspace{1cm}
Version 1.0 \textbf{DRAFT}\\
\today
\vspace{3.0cm}
\end{center}
%
% Empty backside of the titlepage
\newpage
\thispagestyle{empty}
\quad